### ISSUE TITLE
[Welcome!]

### ISSUE THREAD

**Issue by Max-ZiLiang** [RealityBending/Onboarding#11]
Name
_**Max**_ (You can call me Zi Liang too)

Cat or Dogs?
_Dogs, but currently cats are growing on me._

Music or Sports?
_Music, sometimes sports. But if sports, must pair with music._

Sushi or Pizza?
_Sushi > Pizza. But they are both good tho._

Wine or Tea?
_Tea, matcha._

Favourite movie?
_The Godfather._

**Comment by DominiqueMakowski** [comment]
Well received @Max-ZiLiang :) as part of the training, can you try to edit your issue message and delete all the stuff that was prewritten?

**Comment by DominiqueMakowski** [comment]
Awesome, closing the issue :)
