### ISSUE TITLE
[Welcome!]

### ISSUE THREAD

**Issue by naomirajagukguk** [RealityBending/Onboarding#16]
----

- **What's your name?** (or more specifically, what do you want us to call you)

Naomi

- **Catos 🐱 or doggos 🐶?**

Both, I can't seem to choose

- **Sport 🏅 or music 🎵?**

MUSIC

- **Pizza 🍕 or sushi 🍣?**

sushi all the way

- **Wine 🍷 or beer 🧋?**

Wine please

- **Favourite movie 🎦?**

Eternal sunshine of  the spotless mind

**Comment by DominiqueMakowski** [comment]
Welcome Naomi :)
