### ISSUE TITLE
[Welcome!]

### ISSUE THREAD

**Issue by max-hikaru** [RealityBending/Onboarding#17]
So for starters, let's create an issue to answer a few questions!

*(PS: this will become public information, so don't spill out any secret or too embarassing anecdotes)* 😬

Best is to remove all of this pre-written text, and just leave the questions and your answers :relaxed:

Use this as an opportunity to showcase your [**markdown (MD)**](https://www.markdownguide.org/cheat-sheet/) skills by using bold, italic and whatnot.

----

- **What's your name?** (or more specifically, what do you want us to call you)

Max

- **Catos 🐱 or doggos 🐶?**

Cattos!

- **Sport 🏅 or music 🎵?**

A bit of both but mainly music!

- **Pizza 🍕 or sushi 🍣?**

Sushi all the way

- **Wine 🍷 or beer 🧋?**

I love wine but it gives me a headache, so generally beer

- **Favourite movie 🎦?**

Chef

**Comment by DominiqueMakowski** [comment]
Nice one, welcome
