### ISSUE TITLE
[Welcome!]

### ISSUE THREAD

**Issue by CatrionaOM** [RealityBending/Onboarding#18]
My name is Catriona, but you can call me **Cat**

I’m on the Sussex Neuroscience PhD Programme :brain:

Interests: 
-	Ongoing activity, thought & experience
-	(En)active Inference 
-	Philosophy of Science
-	Complex systems & criticality
-	Altered states of consciousness
-	Mental health, critical psychiatry 
-	Evolution of cognition

Education:
-	BSc Neuroscience, 2021 (1st, academic prize. Project: Investigating pronociceptive role of neutrophils in development of chronic pain) 
-	MRes Neuroscience, 2023 (Distinction. Project: Investigating the effects of neural activity on developmental gene expression)
-	Neuroscience PhD, 2023-

A few influences (_maybe_ more than a few :sweat_smile:):
-	Andy Clark
-	Douglas Hofstadter
-	Gabor Maté
-	György Buzsáki
-	Joanna Moncrieff
-	Kalina Christoff
-	Karl Friston
-	Michael Karchoff
-	Randy Gallistel
-	Stanislas Dehaene
-	William Uttal

Other interests: 
-	Coffee and cooking :seedling:
-	Walking, foraging, photography :mushroom:
-	Strength training, bouldering, slacklining & juggling :weight_lifting:

**Comment by DominiqueMakowski** [comment]
Hi @CatrionaOM, welcome 👐 !!
