### ISSUE TITLE
[Welcome! r-dickinson]

### ISSUE THREAD

**Issue by r-dickinson** [RealityBending/Onboarding#19]
- **What's your name?** (or more specifically, what do you want us to call you)

*Rob*

- **Catos 🐱 or doggos 🐶?**

Dogs

- **Sport 🏅 or music 🎵?**

cycling, weight lifting, yoga, bouldering
folk piano or rap

- **Pizza 🍕 or sushi 🍣?**

sushi (check out [](https://tropical-sushi.com/))

- **Wine 🍷 or beer 🧋?**

1. Blue Moon
2. a crisp floral white wine
3. port
4. *alternatives* (meditation, obviously)

- **Favourite movie 🎦?**

The Big Short

**Comment by DominiqueMakowski** [comment]
Hi Rob and welcome to GitHub :)
