### ISSUE TITLE
[Welcome!]

### ISSUE THREAD

**Issue by SofiaTurcany** [RealityBending/Onboarding#23]
----

- **What's your name?** (or more specifically, what do you want us to call you)

Sofia

- **Catos 🐱 or doggos 🐶?**

Dogs

- **Sport 🏅 or music 🎵?**

Sports

- **Pizza 🍕 or sushi 🍣?**

Pizza

- **Wine 🍷 or beer 🧋?**

None

- **Favourite movie 🎦?**

Interstellar

**Comment by DominiqueMakowski** [comment]
Welcome Sofia!
