### ISSUE TITLE
[Welcome!]

### ISSUE THREAD

**Issue by EmmaLBenn** [RealityBending/Onboarding#24]
- **What's your name?** (or more specifically, what do you want us to call you)

Emma

- **Catos 🐱 or doggos 🐶?**

Dogs

- **Sport 🏅 or music 🎵?**

Music

- **Pizza 🍕 or sushi 🍣?**

Pizza

- **Wine 🍷 or beer 🧋?**

Wine

- **Favourite movie 🎦?**

Howl's Moving Castle

**Comment by DominiqueMakowski** [comment]
Nice one, welcome @EmmaLBenn ☺️
