### ISSUE TITLE
[Welcome!]

### ISSUE THREAD

**Issue by bmt997** [RealityBending/Onboarding#26]
- **What's your name?** (or more specifically, what do you want us to call you)

Ben

- **Catos 🐱 or doggos 🐶?**

Doggos 💯

- **Sport 🏅 or music 🎵?**

Music

- **Pizza 🍕 or sushi 🍣?**

Pizza

- **Wine 🍷 or beer 🧋?**

Sparkling water 

- **Favourite movie 🎦?**

In terms of cinematography, probably _We need to talk about Kevin_, in terms of storyline I couldn't choose

**Comment by DominiqueMakowski** [comment]
Welcome to the team 🥳
