### ISSUE TITLE
[Hello!]

### ISSUE THREAD

**Issue by KarlaWall** [RealityBending/Onboarding#28]
- **What's your name?** (or more specifically, what do you want us to call you)

Karla

- **Catos 🐱 or doggos 🐶?**

Cats **100%**

- **Sport 🏅 or music 🎵?**

Music although I don't have so much a taste, I more just listen to the same song for hours on end..

- **Pizza 🍕 or sushi 🍣?**

Pizza and it *has* to be with pineapple. 

- **Wine 🍷 or beer 🧋?**

*Wine* not both.

- **Favourite movie 🎦?**

Changes all the time but at the moment its Whiplash!

**Comment by DominiqueMakowski** [comment]
Welcome to the team @KarlaWall (I do really appreciate the wine pun 👌 )
