### ISSUE TITLE
[Welcome!]

### ISSUE THREAD

**Issue by maisiebennett** [RealityBending/Onboarding#30]
- **What's your name?** (or more specifically, what do you want us to call you)

**Maisie**

- **Catos 🐱 or doggos 🐶?**

I have a cat and a dog, don't make me pick!

- **Sport 🏅 or music 🎵?**

I love watching rugby but nothing beats live music. 

- **Pizza 🍕 or sushi 🍣?**

I love both but sushi is my favourite.

- **Wine 🍷 or beer 🧋?**

Cider 

- **Favourite movie 🎦?**

*Howl's moving castle*

**Comment by DominiqueMakowski** [comment]
Welcome Maisie 🤗
